#!/usr/bin/env bash
# Accept 2 arguments, a domain (required) and a subdomain (optional)
# and output information about the DNS record.

# Print dns record infos.
print_dns_record () {
	record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '(NR>1)' | awk '{print $4" record and points to "$NF}');
	echo "The subdomain $2 is a $record";
}

if [[ $# -eq 1 ]];
then
	for subdomain in www lb-01 web-01 web-02
	do
		print_dns_record "$1" "$subdomain";
	done
elif [[ $# -gt 1 ]];
then
	print_dns_record "$1" "$2";
fi
