#!/usr/bin/env bash
# Install and configure nginx web server.

# Install nginx
#apt-get update
apt-get install -y nginx

# Create the html page to serve.
mkdir -p /var/www/hello_world
echo "Hello World!" > /var/www/hello_world/index.html

# Configure nginx to serve that page.
cat << EOF > /etc/nginx/sites-enabled/default
server {
	listen 80 default_server;
        listen [::]:80 default_server;
	location / {
		root /var/www/hello_world;
		index index.html;
	}
}
EOF

# Reload nginx
nginx -s reload
