#!/usr/bin/env bash
# Install nginx on a server.
sudo apt-get update
sudo apt-get -y install nginx

sudo cat << EOF | sudo tee /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	server_name _;

	location =/ {
		return 200 "Hello World!\n";
	}
}
EOF

#sudo nginx -s reload
sudo service nginx restart    
