#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx

sudo cat << EOF | sudo tee /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	server_name _;
	rewrite ^/redirect_me\/?$ https://www.youtube.com permanent;

	location =/ {
		return 200 "Hello World!\n";
	}

	location / {
		return 404 "Ceci n'est pas une page\n\n";
	}
}
EOF

sudo service nginx restart
