#!/usr/bin/env bash
# Install and configure nginx web server.
# WARNING: This script must be executed with sudo mode.

# Install nginx
apt-get update && apt-get install -y nginx

# Create the html pages to serve.
mkdir -p /var/www/hello_world
echo "Hello World!" > /var/www/hello_world/index.html
echo "Ceci n'est pas une page" > /var/www/hello_world/404.html
echo "" >> /var/www/hello_world/404.html

# Configure nginx to serve that page.
cat << EOF > /etc/nginx/sites-enabled/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/hello_world;
	error_page 404 /404.html;

	location = / {
		index index.html;
	}

	# redirect using a return directive.
	#location /redirect_me {
	#	return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
	#}

	# Redirect with a rewrite directive.
	# Default to a temporary redirect (status 302).
	# The flag permanent instructs a permanent one (status 301).
	rewrite ^/redirect_me$ http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
EOF

# Reload nginx
service nginx restart
#nginx -s reload
