#!/usr/bin/env bash
# Configure nginx in a brand new Ubuntu machine.
sudo apt-get update
sudo apt-get -y install nginx


sudo cat << EOF | sudo tee /var/www/html/index.html
<!DOCTYPE html>
<html>
	<head></head>
	<body>
		<h1>Hello world!</h1>
	</body>
</html>
EOF

sudo cat << EOF | sudo tee /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	server_name _;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html/;
	location / {
		try_files \$uri \$uri/ \$uri.html =404;
	}
}
EOF

sudo service nginx restart
