#!/usr/bin/env bash
# Configure nginx with a custome header in each response.
# WARNING: This script must be executed with sudo mode.

# Install nginx
apt-get update && apt-get install -y nginx

# Create the html pages to serve.
mkdir -p /var/www/hello_world
echo "Hello World!" > /var/www/hello_world/index.html
echo "Ceci n'est pas une page" > /var/www/hello_world/404.html
echo "" >> /var/www/hello_world/404.html

# Configure nginx to serve that page.
cat << EOF > /etc/nginx/sites-enabled/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/hello_world;

	error_page 404 /404.html;

	add_header X-Served-By $HOSTNAME;

	location = / {
		index index.html;
	}

	location /redirect_me {
		return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
EOF

# Reload nginx
service nginx restart
