#!/usr/bin/env bash
# Install and configure HAproxy on an ubuntu server.
sudo apt update
sudo apt -y install haproxy

cat << EOF | sudo tee /etc/haproxy/haproxy.cfg
defaults
	mode http
	option dontlognull
	option redispatch
	option contstats
	balance roundrobin

	# wait for up to 30 seconds in the queue, after which HAProxy returns a 503 Service Unavailable.
	timeout queue 30s

	# within 10 seconds of inactivity (e.g: not sending reponses or response headers) , the client will receive a 504 Gateway timeout error from HAProxy.
	timeout server 10s
	
	# Attempt to connect to the server 4 times before giving up and returning Service Unavailable to the client.
	retries 5

	# 5 second max to connect or to stay in queue.
	timeout connect 5s

	timeout client 30s

	timeout http-keep-alive 5s
	timeout http-request 15s
	backlog 10000

frontend lb-01
	bind *:80
	timeout client 60s
	mode http
	default_backend servers
	maxconn 1000

frontend stats
        mode http
        bind *:8404
        stats enable
        stats uri /stats
        stats refresh 10s
        stats admin if LOCALHOST

backend servers
	mode http
	balance roundrobin
	option httpchk port 80
	http-check send meth GET uri /
	server web-01 100.25.13.40:80 check port 80 maxconn 1000 maxqueue 100
	server web-02 54.162.241.237:80 check port 80 maxconn 1000 maxqueue 100
EOF

echo "ENABLED=1" > /etc/default/haproxy
sudo systemctl enable haproxy.service
sudo systemctl restart haproxy.service
