#!/usr/bin/env bash
# Bash script to fix the server so that it must be running, and listening on port 80 of all the server’s active IPv4 IPs.

# Recreate the /var/run/nginx.pid (deleted by sandbox script) with the nginx master pid.
pgrep nginx* -l | head -n1 | awk '{print $1}' | sudo tee /var/run/nginx.pid 

# Set the default configuration so that nginx listen on *:80 not on *:8080
sudo ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Reload nginx to make the changes take effect.
sudo nginx -s reload
