#!/usr/bin/env bash
# Bash script to fix the server so that it must be running, and listening on port 80 of all the server’s active IPv4 IPs.
pgrep nginx* -l | head -n1 | awk '{print $1}' | sudo tee /var/run/nginx.pid
sudo ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -s reload
rm /var/run/nginx.pid
