#!/usr/bin/env bash
# Print a "To infinity and beyond" consiniously and
# responds to SIGTERM signal  by printing "I am invincible!!!"


trap  "echo 'I am invincible!!!'" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
