#!/usr/bin/env bash
# Displays the content of the file /etc/passwd,
# using the while loop + IFS. Format bellow :
# The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY
# and rides COMMAND/SHELL. USER ID's place is protected by the passcode
# PASSWORD, more info about the user here: USER ID INFO


filename="/etc/passwd"
while IFS= read -r line;
do
	IFS=':' read -r -a arr <<< "$line"
	str="The user ${arr[0]} is part of the ${arr[3]} gang, "
	str+="lives in ${arr[5]} and rides ${arr[6]}. ${arr[2]}'s "
	str+="place is protected by the passcode ${arr[1]}, more "
	str+="info about the user here: ${arr[4]}"
	echo "$str";
done < $filename
