#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59


i=0
while (( "$i" <= 12 )); do
	echo "Hour: $i"
	j=1
	while (( "$j" <= 59 )); do
		echo "$j"
		(( j += 1))
	done
	(( i += 1))
done
