#!/usr/bin/env bash
# Displays the content of the current directory in a list format
# where only  the part of the name after the first dash is displayed.

LIST="$(ls ./)"
for file in $LIST; do
	cut -d "-" -f 2- <<< "$file";
done;
